# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 3 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: jinheeway # jekyll-seo-tag > Owners twitter username
author: jinheeway # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: David Darnes # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/jinheeway
    - https://www.linkedin.com/in/jinhee-chung
    - https://github.com/JinheeC

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Seoul # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to this blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Jinhee's Blog" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "개발중 개인 기록용 블로그이며 내용 수정 및 질문은 왼쪽 하단의 메일전송 또는 아래의 아이콘을 통해 가능합니다." # Site description and default description, also used in jekyll-seo-tag
url: "https://jinheec.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/jinheec/jinheec.github.io"
email: "jinheeway@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://gravatar.com/avatar/93318072ab2e4021cd5a643137b79578" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  About Me: /about/
  Blog: /blog/
  Categories: /categories/
  Search: /search/
#  Fork Alembic: https://github.com/daviddarnes/alembic

navigation_footer:
  Created by Jinhee: https://jinheec.github.io/about/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/jinheeway
  LinkedIn: https://www.linkedin.com/in/jinhee-chung
  GitHub: https://github.com/JinheeC
  RSS: /feed.xml
  #  Google+: https://plus.google.com/+DavidDarnes
#  link: https://darn.es

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  LinkedIn: "#0077B5"
  #facebook: "#3B5998"
  #  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
